site_name: Onesec
site_url: https://xiexunbit.github.io/Study_notes/
nav:
    - Home: index.md
    - 'Notes': 
        - 'C_language': 'study_notes/C_language.md'
        - 'FreeRTOS': 'study_notes/FreeRTOS.md'
        - 'LVGL': 'study_notes/LVGL.md'
        - 'STM32': 'study_notes/STM32.md'
        - 'SRAM': 'study_notes/SRAM.md'
        - 'LCD': 'study_notes/LCD.md'
    - About: about.md
    
theme: 
    name: mkdocs
